development:
  adapter: mysql
  database: turkopticon_devel
  host: localhost
  username: turkopticon_dev
  password: your_password

production:
  adapter: mysql
  database: turkopticon_production
  host: localhost
  username: user
  password: password
